# Generated by Django 5.0 on 2025-03-10 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique identifier for the payment transaction', max_length=500, unique=True, verbose_name='transaction ID')),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid in the transaction', max_digits=10, verbose_name='total amount')),
                ('payment_via', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('bank', 'Bank Transfer'), ('card', 'Credit Card'), ('cash', 'Cash Payment')], help_text='Method used for the payment', max_length=20, verbose_name='payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was recorded', verbose_name='created at')),
                ('is_successful', models.BooleanField(default=True, help_text='Indicates if the payment was successful', verbose_name='successful')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment details in JSON format', verbose_name='metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transaction_id'], name='payments_pa_transac_1e5998_idx'), models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_f9c7f4_idx')],
            },
        ),
    ]
