services:
  - type: web
    name: hotel-booking
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hotel_booking.wsgi:application"
    pythonVersion: 3.10
