services:
  - type: web
    name: hotel-booking
    env: python
    buildCommand: "./.render/build.sh"
    startCommand: "gunicorn hotel_booking.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hotel_booking.settings

