services:
  - type: web
    name: hotel-booking
    env: python
    buildCommand: "./env/bin/pip install -r requirements.txt"
    startCommand: "./env/bin/gunicorn hotel_booking.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
