services:
  - type: web
    name: hotel-booking
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn hotel_booking.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10