# Generated by Django 5.0 on 2025-02-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='images/profile/default-avatar.png', upload_to='images/profile'),
        ),
    ]
