# Generated by Django 5.0 on 2025-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='image',
            field=models.ImageField(upload_to='images/hotels'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='image',
            field=models.ImageField(upload_to='images/rooms'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
