# Generated by Django 5.0 on 2025-01-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_alter_hotelmodel_image_alter_roommodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelmodel",
            name="image",
            field=models.ImageField(
                default="images/hotels/default.jpg", upload_to="images/hotels"
            ),
        ),
        migrations.AlterField(
            model_name="roommodel",
            name="image",
            field=models.ImageField(
                default="images/rooms/default.jpg", upload_to="images/rooms"
            ),
        ),
    ]
