# Generated by Django 5.0 on 2025-03-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_room_additional_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='images/hotels/default.jpg', help_text='Main image of the hotel', upload_to='images/hotels/', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='images/rooms/default.jpg', help_text='Main image of the room', upload_to='images/rooms/', verbose_name='Primary Image'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(help_text='Upload a high-quality image of the hotel', upload_to='images/hotels/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(help_text='Upload a high-quality image of the room', upload_to='images/rooms/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
