# Generated by Django 5.0 on 2025-02-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotelmodel_image_alter_roommodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='no_of_rooms',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
