# Generated by Django 5.0 on 2025-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotelmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='no_of_guests',
        ),
    ]
